#pragma once


// SKETCHY WORK, need the new computer




struct GlExtFuncs {
  PFNGLTEXIMAGE3DEXTPROC glTexImage3D;
  //Compressed Textures
  PFNGLCOMPRESSEDTEXIMAGE3DARBPROC    glCompressedTexImage3DARB;
  PFNGLCOMPRESSEDTEXIMAGE2DARBPROC    glCompressedTexImage2DARB;
  PFNGLCOMPRESSEDTEXIMAGE1DARBPROC    glCompressedTexImage1DARB;
  PFNGLCOMPRESSEDTEXSUBIMAGE3DARBPROC glCompressedTexSubImage3DARB;
  PFNGLCOMPRESSEDTEXSUBIMAGE2DARBPROC glCompressedTexSubImage2DARB;
  PFNGLCOMPRESSEDTEXSUBIMAGE1DARBPROC glCompressedTexSubImage1DARB;
  PFNGLGETCOMPRESSEDTEXIMAGEARBPROC   glGetCompressedTexImageARB;
  //Index Color Tex
  //PFNGLCOLORTABLEEXTPROC glColorTableEXT = NULL;
  //PFNGLGETCOLORTABLEPARAMETERIVEXTPROC glGetColorTableParameterivEXT = NULL;

  //Multi Textures
  PFNGLMULTITEXCOORD1FARBPROC glMultiTexCoord1fARB;
  PFNGLMULTITEXCOORD2FARBPROC glMultiTexCoord2fARB;
  PFNGLMULTITEXCOORD3FARBPROC glMultiTexCoord3fARB;
  PFNGLMULTITEXCOORD4FARBPROC glMultiTexCoord4fARB;
  PFNGLACTIVETEXTUREARBPROC glActiveTextureARB;
  PFNGLCLIENTACTIVETEXTUREARBPROC	glClientActiveTextureARB;
  //VBO
  PFNGLBINDBUFFERARBPROC glBindBufferARB;
  PFNGLBUFFERDATAARBPROC glBufferDataARB;
  PFNGLGENBUFFERSARBPROC glGenBuffersARB;
  PFNGLMAPBUFFERARBPROC glMapBufferARB;
  PFNGLUNMAPBUFFERARBPROC glUnmapBufferARB;
  PFNGLISBUFFERARBPROC glIsBufferARB;
  PFNGLDELETEBUFFERSARBPROC glDeleteBuffersARB;
  //Particle System
  PFNGLPOINTPARAMETERFPROC glPointParameterf;
  PFNGLPOINTPARAMETERFVPROC glPointParameterfv;
  GlExtFuncs();
}; 






